
export const routesByCity = [
  {
    cityName: "Haldwani/Rudrapur",
    routes: [
      {
        to: "Dehradun",
        time: 6,
        distance: 170,
        extraPrice: 12,
        price: 4500,
      },
      {
        to: "Haridwaar",
        time: 6,
        distance: 170,
        extraPrice: 12,
        price: 1500,
      },
      {
        to: "Roorkee",
        time: 6,
        distance: 170,
        extraPrice: 12,
        price: 1500,
      },
      {
        to: "Bageshwar",
        time: 6,
        distance: 170,
        extraPrice: 12,
        price: 1500,
      },
      {
        to: "Pithoragarh",
        time: 10,
        distance: 450,
        extraPrice: 15,
        price: 2000,
      },
      {
        to: "Delhi",
        time: 6,
        distance: 170,
        extraPrice: 12,
        price: 1500,
      },
      {
        to: "Almora",
        time: 6,
        distance: 170,
        extraPrice: 12,
        price: 1500,
      },
    ],
  },
  {
    cityName: "Pithoragarh",
    routes: [
      {
        to: "Dehradun",
        time: 6,
        distance: 170,
        extraPrice: 12,
        price: 2000,
      },
      {
        to: "Haldwani/Rudrapur",
        time: 6,
        distance: 170,
        extraPrice: 12,
        price: 1000,
      },
      {
        to: "Delhi",
        time: 6,
        distance: 170,
        extraPrice: 12,
        price: 2000,
      },
      {
        to: "Almora",
        time: 6,
        distance: 170,
        extraPrice: 12,
        price: 800,
      },
      {
        to: "Roorkee",
        time: 6,
        distance: 170,
        extraPrice: 12,
        price: 2000,
      },
      {
        to: "Haridwaar",
        time: 6,
        distance: 170,
        extraPrice: 12,
        price: 2000,
      },
      {
        to: "Bageshwar",
        time: 6,
        distance: 170,
        extraPrice: 12,
        price: 1000,
      },
    ],
  },
  {
    cityName: "Delhi",
    routes: [
      {
        to: "Dehradun",
        time: 6,
        distance: 170,
        extraPrice: 12,
        price: 4500,
      },
      {
        to: "Haldwani",
        time: 6,
        distance: 170,
        extraPrice: 12,
        price: 4500,
      },
      {
        to: "Pithoragarh",
        time: 6,
        distance: 170,
        extraPrice: 12,
        price: 2000,
      },
      {
        to: "Almora",
        time: 6,
        distance: 170,
        extraPrice: 12,
        price: 2000,
      },
      {
        to: "Haridwaar",
        time: 6,
        distance: 170,
        extraPrice: 12,
        price: 4500,
      },
      {
        to: "Bageshwar",
        time: 6,
        distance: 170,
        extraPrice: 12,
        price: 2000,
      },
    ],
  },
  {
    cityName: "Almora",
    routes: [
      {
        to: "Dehradun",
        time: 6,
        distance: 170,
        extraPrice: 12,
        price: 2000,
      },
      {
        to: "Haldwani",
        time: 6,
        distance: 170,
        extraPrice: 12,
        price: 800,
      },
      {
        to: "Pithoragarh",
        time: 6,
        distance: 170,
        extraPrice: 12,
        price: 800,
      },
      {
        to: "Delhi",
        time: 6,
        distance: 170,
        extraPrice: 12,
        price: 2000,
      },
      {
        to: "Haridwaar",
        time: 6,
        distance: 170,
        extraPrice: 12,
        price: 2000,
      },
      {
        to: "Bageshwar",
        time: 6,
        distance: 170,
        extraPrice: 12,
        price: 4500,
      },
    ],
  },
];
